server {
    listen 8080;
    server_name localhost;
    
    root www;       # This points to your www folder
    index index.html; # This tells it to load index.html if you request "/"

    location / {
        limit_except GET {
		deny all;
	}
    }
}
